name: HypraChart Production Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: hypra-chart-server
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npm run build prod

      - name: Uploading files
        run: |
          mkdir -p /var/www/app-production/server
          rm -r /var/www/app-production/server
          cp -R ./ /var/www/app-production/server
          pm2 restart "server.ecosystem.config.js"
